services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  ws-server:
    build:
      context: ./ws
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: unless-stopped

    ports:
      - "8085:8085"

  engine-server:
    build:
      context: ./engine
      dockerfile: Dockerfile
    depends_on:
      - redis
      - ws-server
    restart: unless-stopped

  express-server:
    build:
      context: ./http
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - "3001:3001"
