name: Build and Push Probo Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Probo Engine Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/engine/
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/probo-engine:latest

      - name: Build and push Probo HTTP Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/http
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/probo-http:latest

      - name: Build and push Probo WebSocket Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/ws
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/probo-ws:latest
